# Generated by Django 5.0.3 on 2024-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(max_length=25)),
            ],
        ),
    ]
